### ISSUE TITLE
serde_dynamo

### ISSUE THREAD

**Issue by bryanburgers** [gabotechs/dynarust#1]
I'm not sure if it would help you here, but just letting you know that [serde_dynamo] exists. It might make some of what you're trying to do a little smoother.

[serde_dynamo]: https://docs.rs/serde_dynamo/latest/serde_dynamo/

**Comment by gabotechs** [comment]
that crate looks really nice! 
The serialization-deserialization in dynarust is very primitive, instead of serializing from `struct` -> `dynamo item` I have this middle step `struct` -> `json value` -> `dynamo item` in which I am relying for doing some operations.
Your crate would definitely be an improvement, specially if I find the need of mapping more complex types, so I will keep an eye on it.
Thanks!
